//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalleReservation
{
    using System;
    using System.Collections.Generic;
    
    public partial class reservation
    {
        public int id_r { get; set; }
        public System.DateTime dateResrv { get; set; }
        public int idU { get; set; }
        public int idS { get; set; }
        public string typeReser { get; set; }
        public string CIN { get; set; }
        public string nom { get; set; }
        public string prenom { get; set; }
        public string email { get; set; }
        public string tele { get; set; }
    
        public virtual salle salle { get; set; }
        public virtual user user { get; set; }
    }
}
